global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'document-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['document_service:8185']
  
  - job_name: 'identity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['identity_service:8085']
      
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
