name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: identity-service
            context: ./backend/services/identity-service
            dockerfile: Dockerfile
          - name: document-service
            context: ./backend/services/document-service
            dockerfile: Dockerfile
          - name: conversion-service
            context: ./backend/services/conversion-service
            dockerfile: Dockerfile
          - name: web-app
            context: ./frontend/web-app
            dockerfile: Dockerfile
          - name: fluentd
            context: ./fluentd
            dockerfile: Dockerfile
          - name: nginx
            context: ./nginx
            dockerfile: Dockerfile
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gestor-e-docs-${{ matrix.name }}:latest
            ghcr.io/${{ github.repository_owner }}/gestor-e-docs-${{ matrix.name }}:${{ github.sha }}