name: Publish Docker images on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: identity-service
            context: ./backend/services/identity-service
            dockerfile: Dockerfile
          - name: document-service
            context: ./backend/services/document-service
            dockerfile: Dockerfile
          - name: conversion-service
            context: ./backend/services/conversion-service
            dockerfile: Dockerfile
          - name: web-app
            context: ./frontend/web-app
            dockerfile: Dockerfile
          - name: fluentd
            context: ./fluentd
            dockerfile: Dockerfile
          - name: nginx
            context: ./nginx
            dockerfile: Dockerfile
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gestor-e-docs-${{ matrix.name }}:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gestor-e-docs-${{ matrix.name }}:latest